config/routes.rb
Barbier::Application.routes.draw do
  
  resources :category_factures

  constraints lambda { |r| r.domain != SalonVar::DOMAIN || (r.subdomain.present? && r.subdomain != 'www') } do
    match '', to: 'accueil#index'  
    
    namespace :prive do
      namespace :site do
        resources :informations
        resource :contact
        resources :photos
        resources :messages do
          member do
            get 'publish'
            get 'unpublish'
          end
        end
        resources :tarifs do
          collection do
            get 'sort'
            post 'reorder'
          end
        end
        resources :tarif_categories do
          collection do
            get 'sort'
            post 'reorder'
          end
        end
        resource :facebook
        resources :themes do
          member do
            get 'use'
          end
          collection do
            get 'use_default'
          end
        end
      end
      match "/site" => redirect("/prive/site/messages")
      
      namespace :options do
        resources :parametres
        match 'facebooks', :to => "facebooks#index"
        resource :facebook, :except => :create do
          get :callback, :to => :create
          collection do
            get 'auth'
            get 'select_page'
            get 'unselect_page'
          end
        end
        resources :sauvegardes do
          collection do
            get 'export'
          end
        end
      end
      match "/options" => redirect("/prive/options/parametres")
      resources :clients
      resources :factures
      resources :option_factures
      resources :category_factures
      namespace :boutique do
        resources :produits
        resources :produit_categories
      end
      match "/boutique" => redirect("/prive/boutique/produits")
      
      # sessions
      # resources :sessions
      get '/login', :to => "sessions#index", :as => 'login'
      post '/login', :to => "sessions#create"
      delete '/logout', :to => "sessions#destroy", :as => 'logout'
            
      match '' => redirect("/prive/clients")
    end
  end
  

  namespace :admin do
    match '/' => redirect("/admin/salons")
    resources :salons
  end

  
  root :to => 'home#index'

end

app/views/shared/_error_messages.erb
<% if target.errors.any? %> 
  <div id="error_explanation">
    <ul> 
      <% target.errors.each do |attr, msg| %>
      <li><%= msg %></li> 
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_facebook_sdk.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/fr_FR/all.js#xfbml=1";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

app/views/shared/_flashbox.erb
<% if notice %>
<div class="alert alert-success"><%= notice %></div>
<% elsif alert %>
<div class="alert alert-error"><%= alert %></div>
<% end %>

app/views/shared/_navbar.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to(@salon.try(:name) || "Salon de coiffure", prive_path, :class => 'brand') %>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse">
        <%= salon_navbar_left_links(params[:controller]) %>
        <ul class="nav pull-right">
          <%= salon_navbar_right_links(params[:controller]) %>
        </ul>
      </div><!-- end of nav-collapse -->
    </div><!-- end of container -->
  </div>
</div>