config/routes.rb
Barbier::Application.routes.draw do
  
  resources :category_factures

  constraints lambda { |r| r.domain != SalonVar::DOMAIN || (r.subdomain.present? && r.subdomain != 'www') } do
    match '', to: 'accueil#index'  
    
    namespace :prive do
      namespace :site do
        resources :informations
        resource :contact
        resources :photos
        resources :messages do
          member do
            get 'publish'
            get 'unpublish'
          end
        end
        resources :tarifs do
          collection do
            get 'sort'
            post 'reorder'
          end
        end
        resources :tarif_categories do
          collection do
            get 'sort'
            post 'reorder'
          end
        end
        resource :facebook
        resources :themes do
          member do
            get 'use'
          end
          collection do
            get 'use_default'
          end
        end
      end
      match "/site" => redirect("/prive/site/messages")
      
      namespace :options do
        resources :parametres
        match 'facebooks', :to => "facebooks#index"
        resource :facebook, :except => :create do
          get :callback, :to => :create
          collection do
            get 'auth'
            get 'select_page'
            get 'unselect_page'
          end
        end
        resources :sauvegardes do
          collection do
            get 'export'
          end
        end
      end
      match "/options" => redirect("/prive/options/parametres")
      resources :clients
      resources :factures
      resources :option_factures
      resources :category_factures
      namespace :boutique do
        resources :produits
        resources :produit_categories
      end
      match "/boutique" => redirect("/prive/boutique/produits")
      
      # sessions
      # resources :sessions
      get '/login', :to => "sessions#index", :as => 'login'
      post '/login', :to => "sessions#create"
      delete '/logout', :to => "sessions#destroy", :as => 'logout'
            
      match '' => redirect("/prive/clients")
    end
  end
  

  namespace :admin do
    match '/' => redirect("/admin/salons")
    resources :salons
  end

  
  root :to => 'home#index'

end

app/controllers/prive/base_controller.rb
module Prive
  class BaseController < ApplicationController
    before_filter :load_salon
    before_filter :authenticate
    
    def authenticate
      if !logged_in?
        redirect_to prive_login_path
      end
    end
    
    def logged_in?
      !!current_salon
    end
    
  end
end

app/controllers/prive/boutique/produit_categories_controller.rb
# encoding: UTF-8
module Prive
  class Boutique::ProduitCategoriesController < BaseController
    layout "site"
    
    def new
      @produit_category = @salon.produit_categories.build
    end


    def create
      @produit_category = @salon.produit_categories.build(params[:produit_category])
      if @produit_category.save
        redirect_to prive_boutique_produits_path, :notice => 'Catégorie ajoutée'
      else
        render :new
      end
    end

    def edit
      @produit_category = @salon.produit_categories.find(params[:id])
    end

    def update 
      @produit_category = @salon.produit_categories.find(params[:id])
      if @produit_category.update_attributes(params[:produit_category])
        redirect_to prive_boutique_produits_path, :notice => 'Catégorie modifiée'
      else
        render :edit
      end
    end

    def destroy
      @produit_category = @salon.produit_categories.find(params[:id])
      @produit_category.destroy
      redirect_to prive_boutique_produits_path, :notice => 'Catégorie supprimée'
    end

  end
end

app/controllers/prive/boutique/produits_controller.rb
# encoding: utf-8
module Prive
  class Boutique::ProduitsController < BaseController
    layout "boutique"

    def index
      @produits_without_category = Produit.where("produit_category_id is null and salon_id = ?", @salon.id)
      @produit_categories = ProduitCategory.includes(:produits).where("produit_categories.salon_id = ?", @salon.id)
    end

    def new
      @produit = @salon.produits.build
    end

    def create
      @produit = @salon.produits.build(params[:produit])
      if @produit.save
        redirect_to prive_boutique_produits_path
      else
        render :new
      end
    end

    def edit
      @produit = @salon.produits.find(params[:id])
    end

    def update
      @produit = @salon.produits.find(params[:id])
      if @produit.update_attributes(params[:produit])
        redirect_to prive_boutique_produits_path
      else
        render :edit
      end
    end

    def destroy
      produit = @salon.produits.find(params[:id])
      produit.destroy
      redirect_to prive_boutique_produits_path, :notice => "Produit supprimé"
    end

  end
end

app/controllers/prive/category_factures_controller.rb
module Prive
  class CategoryFacturesController < BaseController

    layout "factures"

    def new
      @category_facture = @salon.category_factures.build
    end

    def create
      @category_facture = @salon.category_factures.build(params[:category_facture])
      if @category_facture.save
        redirect_to prive_option_factures_path
      else
        render :new
      end
    end

    def destroy
      category_facture = @salon.category_factures.find(params[:id])
      category_facture.destroy
      redirect_to prive_option_factures_path
    end
  end
end

app/controllers/prive/clients_controller.rb
# encoding: utf-8
module Prive
  class ClientsController < BaseController
  
    def index
      @birthday_customers = @salon.clients.has_is_birthday_this_week
      @birthday_customers_grouped_by_dates = @salon.clients.has_is_birthday_this_week_grouped_by_date_and_sorted 
      @clients = @salon.clients.search(params[:search]).paginate(:page => params[:page], :per_page => 20)
    end
  
    def show
      @client = @salon.clients.find(params[:id])
      @factures = @client.factures
    end
  
    def new
      @client = @salon.clients.build
    end
  
    def create
      @client = @salon.clients.build(params[:client])
      if @client.save
        redirect_to prive_client_path(@client)
      else
        render :new
      end
    end
  
    def edit
      @client = @salon.clients.find(params[:id])
    end
  
    def update
      @client = @salon.clients.find(params[:id])
      if @client.update_attributes(params[:client])
        redirect_to prive_client_path(@client)
      else
        render :edit
      end
    end
  
    def destroy
      client = @salon.clients.find(params[:id])
      client.destroy
      redirect_to prive_clients_path, :notice => "Fiche client supprimée"
    end
  
  end
end

app/controllers/prive/factures_controller.rb
# encoding: utf-8
module Prive
  class FacturesController < BaseController

    layout "factures"

    before_filter :get_client

    def index
      @date = params[:date] ? Date.parse(params[:date]) : Date.today
      @period = params[:period] ? params[:period] : 'day'
      
      @factures = Facture.find_by_date_and_period(@date, @period, @salon)
      @services = Item.services_in_factures(@factures)
      @items = Item.where("facture_id IN (?)", @factures.map(&:id)).group_by(&:category)
      respond_to do |format|
        format.html
        format.xls
      end
    end

    def new
      session[:return_to] = request.referer
      @facture = @salon.factures.build(:payed_at => Date.today)
      @facture.items.build
    end

    def create
      params[:facture]["salon_id"] = @salon.id
      params[:facture]["client_id"] = @client.id if @client
      params[:facture]["items_attributes"].each{|key, value| params[:facture]['items_attributes'][key]['salon_id'] = @salon.id }

      @facture = Facture.new(params[:facture])
      if @facture.save
        redirect_to session[:return_to], :notice => "Facture créée"
      else
        logger.debug "CLIENT : #{@client}"
        render :new
      end
    end

    def edit
      session[:return_to] = request.referer
      @facture = @salon.factures.find(params[:id])
    end

    def update
      params[:facture]["salon_id"] = @salon.id
      params[:facture]["client_id"] = @client.id if @client
      params[:facture]["items_attributes"].each{|key, value| params[:facture]['items_attributes'][key]['salon_id'] = @salon.id }

      @facture = @salon.factures.find(params[:id])
      if @facture.update_attributes(params[:facture])
        #if @client
        #  redirect_to prive_client_path(@client), :notice => "Facture modifiée"
        #else
        #  redirect_to prive_factures_path, :notice => "Facture modifiée"
        #end
        redirect_to session[:return_to], :notice => "Facture modifiée"
      else
        render :edit
      end
    end

    def destroy
      @facture = @salon.factures.find(params[:id])
      @facture.destroy
      if @client
        redirect_to prive_client_path(@client), :notice => "Facture supprimée"
      else
        redirect_to prive_factures_path, :notice => "Facture supprimée"
      end
    end

    protected

    def get_client
      if params[:client_id]
        @client = @salon.clients.find(params[:client_id])
      end
    end

  end
end

app/controllers/prive/option_factures_controller.rb
# encoding: utf-8
module Prive
  class OptionFacturesController < BaseController

    layout "factures"

    def index
      @category_factures = @salon.category_factures
    end

  end
end

app/controllers/prive/options/facebooks_controller.rb
# encoding: UTF-8
require 'rack/oauth2'

module Prive
  class Options::FacebooksController < BaseController
    layout "options"
    
    before_filter :get_fb_user, :only => [:index, :select_page, :unselect_page]
    #rescue_from OAuthException, :with => :oauth2_error
    #rescue_from Rack::OAuth2::Client::Error, :with => :oauth2_error
    rescue_from FbGraph::Unauthorized, :with => :oauth2_error
    
    def index
      if @fb_user
        @user = FbGraph::User.new(@fb_user.identifier, :access_token => @fb_user.access_token).fetch 
        if @user && !@fb_user.page_name.present?
          @pages = @user.accounts
        end
      end
    end
    
    def auth
      auth = FacebookAccount.auth.from_cookie(cookies)
      FacebookAccount.identify(auth.user, @salon.id)
      redirect_to prive_options_facebooks_path, :notice => 'La page facebook est liée au compte'
    end
    
    # handle Normal OAuth flow: start
    def new
      client = FacebookAccount.auth(callback_prive_options_facebook_url).client
      redirect_to client.authorization_uri(:scope => SalonVar::FACEBOOK_SCOPE)
    end

    # handle Normal OAuth flow: callback
    def create
      client = FacebookAccount.auth(callback_prive_options_facebook_url).client
      client.authorization_code = params[:code]
      access_token = client.access_token!
      user = FbGraph::User.me(access_token).fetch
      FacebookAccount.identify(user, @salon.id)
      redirect_to prive_options_facebooks_path, :notice => "La page facebook est liée au compte"
    end
    
    def update
      if @salon.update_attributes(params[:facebook])
        redirect_to prive_options_facebooks_path, :notice => "Mis à jour"
      else
        render :index
      end
    end
    
    def destroy
      @fb_user = FacebookAccount.where(:salon_id => @salon.id).first
      @fb_user.destroy
      redirect_to prive_options_facebooks_path
    end
    
    def select_page
      @page = FbGraph::Page.fetch(params[:page_id])
      @fb_user.update_page!(@page, params[:page_access_token])
      redirect_to prive_options_facebooks_path
    end
    
    def unselect_page
      @fb_user.remove_page!
      redirect_to prive_options_facebooks_path
    end
    
    private

    def get_fb_user
      @fb_user = FacebookAccount.where(:salon_id => @salon.id).first
    end
    
    def oauth2_error(e)
      logger.debug("ERROR MESSAGE : #{e.message}")
      if e.message =~/Error validating access token/
        logger.debug("ERROR ACCESS TOKEN")
        redirect_to new_prive_options_facebook_path, :alert => "Erreur Facebook : la connexion a été interrompue"
      else
        redirect_to prive_options_parametres_path, :alert => "Erreur Facebook : #{e.message}"
      end
    end

  end
end

app/controllers/prive/options/informations_controller.rb
# encoding: UTF-8
module Prive
  class Options::InformationsController < BaseController
    layout "options"
    
    def index
    end
    
    def update
      if @salon.update_attributes(params[:salon])
        redirect_to prive_options_informations_path, :notice => "Informations mises à jour"
      else
        render :index
      end
    end
    
  end
end

app/controllers/prive/options/parametres_controller.rb
# encoding: UTF-8
module Prive
  class Options::ParametresController < BaseController
    layout "options"
    
    def index
    end
    
    def update
      if @salon.update_attributes(params[:salon])
        redirect_to prive_options_parametres_url(:subdomain => @salon.subdomain), :notice => "Parametres enregistés"
      else
        render :index
      end
    end
    
  end
end

app/controllers/prive/options/sauvegardes_controller.rb
# encoding: utf-8
require 'csv'

module Prive
  class Options::SauvegardesController < BaseController
    layout "options"
    
    def index
    end
    
    def export
      @outfile = "clients_" + Time.now.strftime("%d-%m-%Y") + ".csv"
      @clients = Client.all
      
      csv_data = CSV.generate({:col_sep => ';'}) do |csv|
        csv << [
          "Nom",
          "Email",
          "Téléphone",
          "Note"
        ]
        @clients.each do |client|
          csv << [
            client.name,
            client.email,
            client.phone,
            client.comment
          ]
        end
      end
      
      send_data csv_data, :type => 'text/csv; charset=utf-8; header=present', :disposition => "attachment; filename=#{@outfile}"
    end
    
  end
end

app/controllers/prive/sessions_controller.rb
module Prive
  class SessionsController < ApplicationController
    before_filter :load_salon
    layout "login"
    
    def index
      redirect_to prive_path if current_salon
    end
    
    def create
      if @salon.authenticate(params[:password])
        session[:salon_id] = @salon.id
        redirect_to prive_path
      else
        redirect_to prive_login_path, :alert => "Mauvais mot de passe"
      end
    end
    
    def destroy
      session[:salon_id] = nil
      @current_user = nil
      redirect_to root_path
    end
    
  end
end

app/controllers/prive/site/contacts_controller.rb
# encoding: UTF-8
module Prive
  class Site::ContactsController < BaseController
    layout "site"
    
    def show
    end
    
    def update
      if @salon.update_attributes(params[:salon])
        redirect_to prive_site_contact_path, :notice => "Données de contact mises à jour"
      else
        render :show
      end
    end
    
  end
end

app/controllers/prive/site/facebooks_controller.rb
# encoding: UTF-8
module Prive
  class Site::FacebooksController < BaseController
    layout "site"
    
    def show
      @facebook_account = @salon.facebook_account
    end
    
    def update
      if @salon.update_attributes(params[:salon])
        redirect_to prive_site_facebook_path, :notice => "Choix enregistrer"
      else
        render :index
      end
    end
    
  end
end

app/controllers/prive/site/informations_controller.rb
# encoding: UTF-8
module Prive
  class Site::InformationsController < BaseController
    layout "site"
    
    def index
    end
    
    def update
      if @salon.update_attributes(params[:salon])
        redirect_to prive_site_informations_path, :notice => "Informations mises à jour"
      else
        render :index
      end
    end
    
  end
end

app/controllers/prive/site/messages_controller.rb
# encoding: UTF-8
require 'rack/oauth2'

module Prive
  class Site::MessagesController < BaseController
    layout "site"
    
    rescue_from FbGraph::Exception, :with => :oauth2_error
    
    def index
      @messages = @salon.messages
    end
    
    def new
      @message = @salon.messages.build
    end
    
    def create
      @message = @salon.messages.build(params[:message])
      if @message.save
        @message.send_to_facebook
        redirect_to prive_site_messages_path, :notice => 'Message ajouté'
      else
        render :new
      end
    end
    
    def edit
      @message = @salon.messages.find(params[:id])
    end
    
    def update
      @message = @salon.messages.find(params[:id])
      if @message.update_attributes(params[:message])
        redirect_to prive_site_messages_path, :notice => 'Message modifié'
      else
        render :edit
      end
    end
    
    def destroy
      message = @salon.messages.find(params[:id])
      message.destroy
      redirect_to prive_site_messages_path, :notice => 'Message supprimé'
    end
    
    def publish
      message = @salon.messages.find(params[:id])
      message.publish!
      message.send_to_facebook
      redirect_to prive_site_messages_path, :notice => 'Message publié'
    end
    
    def unpublish
      message = @salon.messages.find(params[:id])
      message.unpublish!
      redirect_to prive_site_messages_path, :notice => 'Message dépublié'
    end
    
    private
    
    def oauth2_error(e)
      logger.debug("ERROR MESSAGE : #{e.message}")
      if e.message =~/Error validating access token/
        logger.debug("ERROR ACCESS TOKEN")
        redirect_to new_prive_options_facebook_path
      else
        redirect_to prive_site_messages_path, :alert => "Erreur Facebook : #{e.message}"
      end
    end
    
  end
end

app/views/prive/factures/_form.erb
<%= render "/shared/error_messages", :target => @facture %>
<% if @client %>
<%= hidden_field_tag :client_id, @client.try(:id) %>
<% end %>
<fieldset>
  <span id="service_description_source" data-autocomplete-source="<%= @salon.unique_items %>"></span>
  <span id="produit_description_source" data-autocomplete-source="<%= @salon.produits.map(&:name) %>"></span>
  <%= f.text_field :payed_at, :class => 'datepicker input-small', :placeholder => "Date" %>
  <%= f.select :mean_of_payment, Facture::MEANS_OF_PAYMENT.map{|mp| [t("factures.mean_of_payment.#{mp}"), mp]} %>
</fieldset>

<%= f.fields_for :items do |builder| -%>
  <%= render "item_fields", f: builder %>
<% end -%>
<p id="add-items">
  <%= link_to_add_fields "Ajouter un service", f, :items %>
  <%= link_to_add_fields "Ajouter un produit", f, :items, "produit", "success" %>
</p>
<br/>

app/views/prive/factures/_item_fields.erb
<div class="">
  <%= f.text_field :description, :placeholder => "Description", :class => "input-xlarge item-description", :data => { :type => f.object.attributes['category']} %>
  <%= f.text_field :price, :placeholder => "Prix", :class => "input-small" %>
  <%= f.select :category, @salon.category_factures.map(&:name) + ["Produit"], {}, :class => "item-category" %>
  <%= f.hidden_field :_destroy %>
  <%= link_to "retirer", '#', class: "remove_fields" %>
</div>

app/views/prive/factures/edit.html.erb
<div id="facture">
  <h1>Modifier la facture</h1>

  <%= form_for [:prive, @facture], :class => 'form-horizontal' do |f| %>

    <%= render "form", :f => f %>

    <div style="clear:both">
      <%= f.submit "Modifier", class: 'btn' %>
      <%= link_to "annuler", session[:return_to] || prive_client_path(@client) %>
    </div>

  <% end %>
</div>

app/views/prive/factures/index.html.erb
<h1>Factures</h1>

<div id="factures">
  <div id="factures-period-controls">
    <div id="factures-period-controls-left">
      <%= link_to ("<i class='icon-plus-sign icon-white'></i>&nbsp;Facture").html_safe, new_prive_facture_path(), class: 'btn btn-success' %>
      <%= display_factures_period_date(@date, @period) %>
    </div>

    <div id="factures-period-controls-right">
      <div id="factures-actions">
        <%= link_to "exporter (xls)", { date: @date, period: @period, format: 'xls' } %>
      </div>
      <div id="factures-period-selector" class="btn-group" data-toggle="buttons-radio" data-period="<%= @period %>">
        <%= link_to 'Jour', { period: 'day', date: @date }, { class: 'btn', id: 'factures-period-day' } %>
        <%= link_to 'Semaine', { period: 'week', date: @date }, { class: 'btn', id: 'factures-period-week' } %>
        <%= link_to 'Mois', { period: 'month', date: @date }, { class: 'btn', id: 'factures-period-month' } %>
      </div>
    </div>
  </div>

  <table class="table table-striped table-bordered">
    <tr>
      <th>Date</th>
      <th>Client</th>
      <% for service in @services %>
        <th><%= service.present? ? service : "Service" %></th>
      <% end %>
      <th>Total</th>
      <th>Moyen de paiement</th>
      <th>Actions</th>
    </tr>
    <tr>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
      <% for service in @services %>
        <th class="currency"><%= number_to_currency(total_items(@items[service])) %></th>
      <% end %>
      <th class="currency"><%= total_factures(@factures) %></th>
      <th>&nbsp;</th>
      <th>&nbsp;</th>
    </tr>
    <% if @factures.any? %>
      <% for facture in @factures -%>
        <tr>
          <td><%= l facture.payed_at %></td>      
          <td><%= link_to_client_of_this_facture(facture) %></td>      

          <% for service in @services %>
          <td class="currency">
            <%= number_to_currency(total_items(facture.items.where("category = ?", service))) %>
          </td>
          <% end %>

          <td class="currency"><%= total_facture(facture) %></td>
          <td><%= t("factures.mean_of_payment.#{facture.mean_of_payment}") %></td>
          <td>
            <%= link_to "modifier", edit_prive_facture_path(facture, :client_id => facture.client.try(:id)) %>
            <%= link_to "supprimer", prive_facture_path(facture), :method => :delete %>
          </td>
        </tr>
      <% end -%>
    <% else %>
      <tr>
        <td colspan="5">Aucune facture</td>
      </tr>
    <% end %>
  </table>
</div>

app/views/prive/factures/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">

  <Styles>
    <Style ss:ID="Default" ss:Name="Normal">
      <Alignment ss:Vertical="Bottom"/>
      <Borders/>
      <Font/>
      <Interior/>
      <NumberFormat/>
      <Protection/>
    </Style>
    <Style ss:ID="s21">
      <Font ss:Bold="1"/>
      <Alignment ss:Horizontal="Center" ss:Vertical="Bottom"/>
    </Style>
    <Style ss:ID="s25">
      <NumberFormat ss:Format="Euro Currency"/>
    </Style>
  </Styles>

  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell ss:StyleID="s21"><Data ss:Type="String">Date</Data></Cell>
        <Cell ss:StyleID="s21"><Data ss:Type="String">Description</Data></Cell>
        <Cell ss:StyleID="s21"><Data ss:Type="String">Prix</Data></Cell>
        <Cell ss:StyleID="s21"><Data ss:Type="String">Moyen de paiement</Data></Cell>
      </Row>
    <% @factures.each do |facture| %>
      <% facture.items.each do |item| %>
        <Row>
          <Cell><Data ss:Type="String"><%= facture.payed_at.strftime("%d/%m/%Y") %></Data></Cell>
          <Cell><Data ss:Type="String"><%= item.description %></Data></Cell>
          <Cell ss:StyleID="s25"><Data ss:Type="Number"><%= item.price %></Data></Cell>
          <Cell><Data ss:Type="String"><%= t("factures.mean_of_payment.#{facture.mean_of_payment}") %></Data></Cell>
        </Row>
      <% end %>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/prive/factures/new.html.erb
<div id="facture">
  <h1>Nouvelle facture</h1>

  <%= form_for [:prive, @facture], :html => { :class => 'form-vertical' } do |f| %>

    <%= render "form", :f => f %>

    <div style="clear:both">
      <%= f.submit "Ajouter", class: 'btn' %>
      <%= link_to "annuler", session[:return_to] || prive_client_path(@client) %>
    </div>

  <% end %>
</div>

app/views/prive/factures/oldtable.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th>Date</th>
    <th>Services</th>
    <th>Total</th>
    <th>Moyen de paiement</th>
    <th>Actions</th>
  </tr>
  <% if @factures.any? %>
    <% for facture in @factures -%>
      <tr>
        <td><%= l facture.payed_at %></td>      
        <td>
          <%=raw facture.items.map{|i| "#{i.description} <span class='price'>#{number_to_currency(i.price)}</span>" }.join('<br/>') %>
        </td>
        <td><%= total_facture(facture) %></td>
        <td><%= t("factures.mean_of_payment.#{facture.mean_of_payment}") %></td>
        <td>
          <%= link_to "modifier", edit_prive_facture_path(facture, :client_id => facture.client.try(:id)) %>
          <%= link_to "supprimer", prive_facture_path(facture), :method => :delete %>
        </td>
      </tr>
    <% end -%>
  <% else %>
    <tr>
      <td colspan="5">Aucune facture</td>
    </tr>
  <% end %>
</table>